name: Gen

# on:
#   schedule:
#     - cron:  '0 4 * * *'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: '2.6'
        architecture: 'x64'
    - name: Run tests
      run: |
        rake -f Rakefile flightxml:generate

        if git diff-index --quiet HEAD --; then
          branch_name="`date "+%Y-%m-%d"`-wsdl-update"
          git checkout -b $branch_name
          git add .
          git commit -m "Regenerate based on updated WSDL"
          git push origin $branch_name

          curl --request POST\
            --url https://api.github.com/repos/jakewilkins/flightxml-json/pulls\
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            --header 'content-type: application/json' \
            --data '{
              "title": "Regenerate for updated WSDL",
              "head": "$branch_name",
              "base": "master",
              "body": "FlightAware published an updated WSDL. This regenerates our code based upon updated definitions"
            }'
        fi
